export const BLOCKS = {
  ROLE: 1,
  GLOBAL_CONSTRAINTS: 2,
  RECENT_DECISIONS: 3,
  ACTIVE_CONSTRAINTS: 4,
  SESSION_CONTEXT: 5,
  OPEN_QUESTIONS: 6,
  STALE_FLAGS: 7,
  SESSION_BOUNDARIES: 8
};

export const BLOCK_TITLES = {
  1: "ROLE",
  2: "GLOBAL_CONSTRAINTS",
  3: "RECENT_DECISIONS",
  4: "ACTIVE_CONSTRAINTS",
  5: "SESSION_CONTEXT",
  6: "OPEN_QUESTIONS",
  7: "STALE_FLAGS",
  8: "SESSION_BOUNDARIES"
};